const SESSION_ID_NAME = '__Host-Http-sid';

const SESSION_ABSOLUTE_TIMEOUT_MS = 24 * 60 * 60 * 1000;
const CLEAR_EXPIRED_ABSOLUTE_TIME_SESSIONS_INTERVAL =
  SESSION_ABSOLUTE_TIMEOUT_MS / 2;

const FAKE_USER = {
  fake: true,
  password: '$2b$10$CXAfzFj2QAz6MnQy8IL3Hu8VeZdXfo2IsmeAKM12MWJzaraGCZUai',
};

const IDLE_TIMEOUT_MS = 1000 * 300;
const CLEAR_EXPIRED_IDLE_TIME_SESSIONS_INTERVAL = 1000 * 300;

export {
  SESSION_ID_NAME,
  SESSION_ABSOLUTE_TIMEOUT_MS,
  FAKE_USER,
  IDLE_TIMEOUT_MS,
  CLEAR_EXPIRED_IDLE_TIME_SESSIONS_INTERVAL,
  CLEAR_EXPIRED_ABSOLUTE_TIME_SESSIONS_INTERVAL,
};
