const SESSION_ID_NAME = '__Host-Http-sid';
const SESSION_ABSOLUTE_TIMEOUT_MS = 24 * 60 * 60 * 1000;

const FAKE_USER = {
  fake: true,
  password: '$2b$10$CXAfzFj2QAz6MnQy8IL3Hu8VeZdXfo2IsmeAKM12MWJzaraGCZUai',
};

const IDLE_TIMEOUT = 1000 * 300;
const CLEAR_EXPIRED_IDLE_TIME_SESSIONS_INTERVAL = IDLE_TIMEOUT;

export {
  SESSION_ID_NAME,
  SESSION_ABSOLUTE_TIMEOUT_MS,
  FAKE_USER,
  IDLE_TIMEOUT,
  CLEAR_EXPIRED_IDLE_TIME_SESSIONS_INTERVAL,
};
