name: CI workflow

on:
  workflow_call:
  pull_request:
    branches: ['dev', 'master']

jobs:
  call-linting-workflow:
    uses: ./.github/workflows/lint-format.yml
  call-tesing-workflow:
    needs: call-linting-workflow
    uses: ./.github/workflows/tests.yml
