name: CI workflow

on:
  workflow_call:
  pull_request:
    branches: ['dev', 'master']

jobs:
  call-lint-format-ts-workflow:
    uses: ./.github/workflows/lint-format-ts.yml
  call-tesing-workflow:
    needs: call-lint-format-ts-workflow
    uses: ./.github/workflows/tests.yml
