name: Lint-workflow

on:
  workflow_call:

jobs:
  lint-format:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/checkout-repo-setup-node
      - name: Pre-deply checks
        run: npm run pre-deploy 
